config/routes.rb
Rails.application.routes.draw do
  # get 'mypage', to: 'users#me'
  post 'login', to: 'sessions#create'
  delete 'logout', to: 'sessions#destroy'
  root 'top#index'
  resources :memories
  resources :users, only: %i[new create]
  post '/memories/:id/toggle' => 'memories#toggle'

  devise_for :users


  resources :memories do

    resources :schedules, only: [:update, :edit, :destroy]


  end

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/schedule.rb
class Schedule < ApplicationRecord
  belongs_to :memory
  validates :schedule, presence: { message: "スケジュール周期を入力してください"}
end

app/controllers/schedules_controller.rb
class SchedulesController < ApplicationController

  

   
  def update
    # @memory =  Memory.find(params[:id])
    schedules = Schedule.find(params[:id])
    
    if  schedules.update(schedule: Time.current.days_since(a.to_i).to_date, schedule_form: a.to_i)
      redirect_to memories_path, notice: '更新が完了しました!'
    else 
      flash[:alert] = '更新できませんでした'
      render :edit
    end
  end



  def destroy
    # binding.pry
    schedules = Schedule.find(params[:id])
    # schedules.destroy
    # binding.pry
    # @schedule_memory_id = Memory.find(params[:memory_id])
    @memory = Memory.find(params[:memory_id])
    
    if @memory.schedules.count == 1
      @memory.destroy
      redirect_to memories_path, notice: 'お疲れ様です！復習スケジュールを完了しました'
    else
      # binding.pry
      schedules.destroy
      
      
      redirect_to memories_path, notice: 'お疲れ様です！復習スケジュールを完了しました'
    end
  end
end

app/views/schedules/index.html.erb
<h2>復習スケジュール一覧</h2>
<div class="row">
  <div class="col-md-12">
    <table class="table table-striped">
      <thead class="thead-light">
        <tr class="index">
          <%# <td>日付</td>
          <td>教材</td>
          <td>学習範囲</td>
        <td>勉強時間</td> %>
        </tr>
      </thead>
      <tbody>
     
        
        <% Schedule.order(date: "ASC").joins(:memory).where(memory: { user_id: current_user.id }).each do |s| %>
            <tr>
              <td><%=  s.schedule %></td>
              <td><%= s.memory.text  %></td>
              <td><%= link_to s.memory.range, memory_path(s.memory) %></td>
              <td><%= s.memory.time %></td>
              <td>[ <%=  link_to '編集する', edit_memory_path(s.memory,s) %> ]</td> 
              <td>[ <%= link_to '完了する', memory_schedules_path(s.memory,s), method: :delete, data:{ confirm: '本当に完了していいですか？' }%> ]</td>
            </tr>   
          <% end %> 
    </tbody>
    </table>
  </div>
</div>

<script>
   $(function(){
     $("input[type=checkbox]").click(function(){
       $.post('/memory/' + $(this).data('id') + '/toggle');
     });
   });
</script>

<%= paginate @schedule %>