config/routes.rb
Rails.application.routes.draw do
  # get 'mypage', to: 'users#me'
  post 'login', to: 'sessions#create'
  delete 'logout', to: 'sessions#destroy'
  root 'top#index'
  resources :memories
  resources :users, only: %i[new create]
  post '/memories/:id/toggle' => 'memories#toggle'

  devise_for :users


  resources :memories do

    resources :schedules, only: [:update, :edit, :destroy]


  end

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/memory.rb
class Memory < ApplicationRecord
  belongs_to :user
  has_many :schedules, dependent: :destroy
  
 

  validates :text, presence: { message: "テキスト名を入力してください"}
  validates :range, presence: { message: "学習範囲を入力してください"}
  validates :time, presence: { message: "学習時間を入力してください"}
  # validates :schedule, presence: { message: "スケジュール周期を入力してください"}
   
  REGISTRABLE_ATTRIBUTES = %i(
    name
    date(1i) date(2i) date(3i)
    published_at(1i) published_at(2i) published_at(3i) published_at(4i) published_at(5i)
  )

  def user
    return User.find_by(id: self.user_id)
  end
end

app/controllers/memories_controller.rb
class MemoriesController < ApplicationController
  before_action :set_target_memory, only: %i[show edit update destroy]

  def index
    @schedules = Schedule.joins(:memory).where(memory: {user_id: current_user.id }).order('schedule asc').page(params[:page]).per(10)


   
    # binding.pry
  end
  
  def new
    @memory = Memory.new
    
  end

  def create
    @memory = Memory.new(memory_params)
    @memory.user_id = current_user.id
    arrays = params[:memory][:schedule].split(",") 

    arrays.each do |a|
      @memory.schedules.build(schedule: Time.current.days_since(a.to_i).to_date, schedule_form: a.to_i)
    end

    if @memory.save
      redirect_to memories_path, notice: '投稿が完了しました!'
    else
      flash[:alert] = '投稿が完了できませんでした'
      render :new 
    end     
  end

  def show
    @memory = Memory.find(params[:id])
  end
  
  def edit
    # binding.pry
    @memory = Memory.find(params[:id])
  end

  def update
    if @memory.update(memory_params)
      redirect_to memories_path, notice: '更新が完了しました!'
    else 
      flash[:alert] = '更新できませんでした'
      render :edit
    end
  end
  
 



  def schedule
    @memory = Memory.new(memory_params)
    @memory.update()
  end

  private
  def memory_params
    params.require(:memory).permit(:date, :text, :time, :range,)
  end

  def schedule_params
    params.require(:schedule).permit(:schedule)
  end


  def set_target_memory
    @memory = Memory.find(params[:id])
  end
end

 

app/views/memories/_form.html.erb
<%= form_with model: @memory, local:true do |f| %>
  <div class="form-group">
    <div div class="ml-auto boards__linkBox">
      <%= link_to '一覧', memories_path, class: 'btn btn-outline-dark' %>
    </div>
  </div>

  <div>
    <label>日付</label>
     <%= f.date_select :date, {}, class: 'form-date' %>
  </div>

  <div class ="form-group">
    <label>教材名</label>
    <%= f.text_field :text, class: "form-control", placeholder: "例: 〇〇単語帳" %>
  </div>

  <div class="form-group">
    <label>学習範囲</label>
    <%= f.text_field :range, class: "form-control", placeholder: "例: 40~56p" %>
  </div> 

  <div class="form-group">
    <label>勉強時間</label>
    <%= f.text_field :time, class: "form-control", placeholder: "例: 2h30m" %>
  </div> 

  <div class="form-group">
    <label>復習スケジュール(学習日から〇日後に復習する)</label>
    <%= f.text_field :schedule, value: f.object.schedules.pluck(:schedule_form).join(','), class: "form-control", placeholder: "例: 1,3,5"%>
  </div> 

  <div class="text-center">
    <%= f.submit "登録する", class: "btn btn-primary" %>
  </div>
<% end %>

app/views/memories/edit.html.erb
<div>
  <div class="col-md-4 offset-md-4">
  <h2 class="text-center">復習スケジュールの編集</h2>
    <%= form_with model: @memory, local:true do |f| %>
      <div class="form-group">
        <div div class="ml-auto boards__linkBox">
          <%= link_to '一覧', memories_path, class: 'btn btn-outline-dark' %>
        </div>
      </div>

      <div class ="form-group">
        <label>教材名</label>
        <%= f.text_field :text, class: "form-control" %>
      </div>

      <div class="form-group">
        <label>学習範囲</label>
        <%= f.text_field :range, class: "form-control" %>
      </div> 

      <div class="form-group">
        <label>勉強時間</label>
        <%= f.text_field :time, class: "form-control" %>
      </div> 

      <div class="text-center">
        <%= f.submit "登録する", class: "btn btn-primary" %>
      </div>
    <% end %>
  </div>
</div>

app/views/memories/index.html.erb
<h2>復習スケジュール一覧</h2>
<div class="row">
  <div class="col-md-12">
    <table class="table table-striped">
      <thead class="thead-light">
        <tr class="index">
          <%# <td>日付</td>
          <td>教材</td>
          <td>学習範囲</td>
        <td>勉強時間</td> %>
        </tr>
      </thead>
      <tbody>
     
        
         
        <% @schedules.order(:date).joins(:memory).each do |s| %>
            <tr>
              <td><%=  s.schedule %></td>
              <td><%= s.memory.text  %></td>
              <td><%= link_to s.memory.range, memory_path(s.memory) %></td>
              <td><%= s.memory.time %></td>
              <td>[ <%=  link_to '編集する', edit_memory_path(s.memory,s) %> ]</td> 
              <td>[ <%= link_to '完了する', memory_schedule_path(s.memory,s), method: :delete, data:{ confirm: '本当に完了していいですか？' }%> ]</td>
            </tr>   
          <% end %> 
    </tbody>
    </table>
  </div>
</div>

<script>
   $(function(){
     $("input[type=checkbox]").click(function(){
       $.post('/memory/' + $(this).data('id') + '/toggle');
     });
   });
</script>

<%= paginate @schedules %>

app/views/memories/new.html.erb
<div>
  <div class="col-md-4 offset-md-4">
  <h2 class="text-center">復習スケジュールの投稿</h2>
  <%= render 'form' %>
  </div>
</div>

app/views/memories/show.html.erb
<div class="row">
  <div class="col-md-12">
    <h2><%= @memory.text %></h2>
  </div>
  <div>
    学習範囲: <%= @memory.range %>
  </div>
  <div>
     勉強時間: <%= @memory.time %>
  </div>
  <%# <div>
     復習スケジュール: <%= @memory.schedule %>
  <%# </div> %> 
  <hr>

  <div>
    <%= link_to '一覧へ戻る', memories_path %>
  </div>
</div>